import type { Plan } from '~/types';

export function generateDemoData(title: string = 'Demo Life Binder (Sample Data)'): Plan {
  const now = new Date().toISOString();
  const futureDate = new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
  const nearFutureDate = new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

  const contact1Id = crypto.randomUUID();
  const contact2Id = crypto.randomUUID();
  const contact3Id = crypto.randomUUID();
  const contact4Id = crypto.randomUUID();

  return {
    id: crypto.randomUUID(),
    title,
    createdAt: now,
    updatedAt: now,
    isEncrypted: true,
    preferences: {
      showEncryptionWarning: true,
      autoLockMinutes: 10,
    },
    contacts: [
      {
        id: contact1Id,
        name: 'Jane Smith',
        relationship: 'Spouse',
        phone: '555-0101',
        email: 'jane.smith@example.com',
        notes: 'Primary contact - knows location of all important documents',
        notifyBeforeSocial: true,
        order: 1,
      },
      {
        id: contact2Id,
        name: 'John Doe',
        relationship: 'Brother',
        phone: '555-0102',
        email: 'john.doe@example.com',
        notes: 'Tech-savvy, can help with digital accounts',
        notifyBeforeSocial: true,
        order: 2,
      },
      {
        id: contact3Id,
        name: 'Sarah Johnson',
        relationship: 'Best Friend',
        phone: '555-0103',
        email: 'sarah.j@example.com',
        notes: 'Can help manage social media accounts',
        notifyBeforeSocial: false,
        order: 3,
      },
      {
        id: contact4Id,
        name: 'Michael Brown',
        relationship: 'Cousin',
        phone: '555-0104',
        email: 'mbrown@example.com',
        notes: 'Lives nearby, can help with physical tasks',
        notifyBeforeSocial: false,
        order: 4,
      },
    ],
    notificationPlan: {
      orderedContactIds: [contact1Id, contact2Id, contact3Id],
      socialMediaDrafts: [
        'EXAMPLE: We regret to inform you that [Name] has passed away. The family appreciates your thoughts and support during this difficult time.',
        'EXAMPLE: Memorial service details will be shared with close friends and family. Please respect the family\'s privacy.',
      ],
      privateMessageDraft: 'EXAMPLE: Dear [Name], I wanted to let you know personally that [Person] has passed away. Details about arrangements will follow. Thank you for your friendship and support.',
    },
    access: {
      primaryEmails: [
        {
          id: crypto.randomUUID(),
          email: 'personal@example.com',
          provider: 'Gmail',
          notes: 'Primary personal email - used for most accounts',
        },
        {
          id: crypto.randomUUID(),
          email: 'work@example.com',
          provider: 'Outlook',
          notes: 'Work email - IT department should be contacted',
        },
      ],
      passwordManagerNotes: 'EXAMPLE: Password vault file located at ~/Documents/Passwords/vault.kdbx\nMaster password hint: childhood pet + graduation year\nBackup codes stored in safe deposit box #12345 at First National Bank',
      twoFANotes: 'EXAMPLE: Authenticator app on iPhone (backed up to iCloud)\nRecovery codes stored in password manager\nSMS backup on phone number ending in -0101',
      devices: [
        {
          id: crypto.randomUUID(),
          type: 'Laptop',
          name: 'MacBook Pro 2022',
          retentionNotes: 'EXAMPLE: Contains work files - return to employer. Personal files backed up to external drive.',
          disposalPlan: 'EXAMPLE: Factory reset after data transfer, return to company IT',
        },
        {
          id: crypto.randomUUID(),
          type: 'Phone',
          name: 'iPhone 14',
          retentionNotes: 'EXAMPLE: Family photos backed up to iCloud. Can be wiped after photo transfer.',
          disposalPlan: 'EXAMPLE: Remove from Find My iPhone, factory reset, can be kept by family or sold',
        },
        {
          id: crypto.randomUUID(),
          type: 'Tablet',
          name: 'iPad Air',
          retentionNotes: 'EXAMPLE: Used primarily for reading. Can be donated or given to family member.',
          disposalPlan: 'EXAMPLE: Sign out of Apple ID, factory reset, donate to library',
        },
      ],
      networkInfrastructure: [
        {
          id: crypto.randomUUID(),
          type: 'Router',
          name: 'Netgear Nighthawk AX12',
          location: 'Hall closet, top shelf',
          accessInfo: 'EXAMPLE: Admin: 192.168.1.1, Username: admin, Password hint: router default + year',
          notes: 'EXAMPLE: ISP: Comcast Business (555-1700), Account #1234567890',
        },
        {
          id: crypto.randomUUID(),
          type: 'NAS',
          name: 'Synology DS920+',
          location: 'Home office closet',
          accessInfo: 'EXAMPLE: Web: nas.local:5000, Admin account credentials in password manager',
          notes: 'EXAMPLE: Contains family photos backup, automatic daily backups configured',
        },
        {
          id: crypto.randomUUID(),
          type: 'Mesh System',
          name: 'Google WiFi (3 nodes)',
          location: 'Living room, bedroom, office',
          accessInfo: 'EXAMPLE: Google Home app on phone, signed in with personal@example.com',
          notes: 'EXAMPLE: Main network name: HomeNetwork_5G',
        },
      ],
      iotDevices: [
        {
          id: crypto.randomUUID(),
          name: 'Smart Thermostat',
          type: 'Climate Control',
          location: 'Hallway',
          accountInfo: 'EXAMPLE: Nest account linked to personal@example.com',
          notes: 'EXAMPLE: Heating/cooling schedules configured, can be controlled remotely',
        },
        {
          id: crypto.randomUUID(),
          name: 'Ring Video Doorbell',
          type: 'Security',
          location: 'Front door',
          accountInfo: 'EXAMPLE: Ring app, subscription active until Dec 2024',
          notes: 'EXAMPLE: Video storage for 60 days, shared access with spouse',
        },
        {
          id: crypto.randomUUID(),
          name: 'Philips Hue Lights',
          type: 'Lighting',
          location: 'Throughout house (12 bulbs)',
          accountInfo: 'EXAMPLE: Hue app, bridge located in TV cabinet',
          notes: 'EXAMPLE: Automated schedules set up, works with voice assistant',
        },
        {
          id: crypto.randomUUID(),
          name: 'August Smart Lock',
          type: 'Access Control',
          location: 'Back door',
          accountInfo: 'EXAMPLE: August app, guest codes can be generated',
          notes: 'EXAMPLE: Auto-lock enabled, backup physical keys in kitchen drawer',
        },
      ],
    },
    accounts: {
      subscriptions: [
        {
          id: crypto.randomUUID(),
          name: 'Netflix',
          type: 'Streaming',
          status: 'review',
          notes: 'EXAMPLE: Family plan - decide if others want to continue',
          contractEndDate: futureDate,
          monthlyFee: 'EXAMPLE: $19.99',
        },
        {
          id: crypto.randomUUID(),
          name: 'Spotify Premium',
          type: 'Music',
          status: 'cancel',
          notes: 'EXAMPLE: Individual account - can be cancelled',
          monthlyFee: 'EXAMPLE: $10.99',
        },
        {
          id: crypto.randomUUID(),
          name: 'Adobe Creative Cloud',
          type: 'Software',
          status: 'cancel',
          notes: 'EXAMPLE: Annual subscription - cancel to avoid renewal',
          contractEndDate: nearFutureDate,
          monthlyFee: 'EXAMPLE: $54.99',
        },
        {
          id: crypto.randomUUID(),
          name: 'Amazon Prime',
          type: 'Shopping',
          status: 'keep',
          notes: 'EXAMPLE: Shared with family - they may want to keep',
          monthlyFee: 'EXAMPLE: $14.99',
        },
      ],
      socialMedia: [
        {
          id: crypto.randomUUID(),
          platform: 'Facebook',
          username: 'john.example',
          disposition: 'memorialize',
          exportInstructions: '',
          notes: 'EXAMPLE: Main social presence - request memorialization',
        },
        {
          id: crypto.randomUUID(),
          platform: 'Instagram',
          username: '@johnexample',
          disposition: 'memorialize',
          exportInstructions: '',
          notes: 'EXAMPLE: Photo archive - family may want to preserve',
        },
        {
          id: crypto.randomUUID(),
          platform: 'Twitter',
          username: '@john_example',
          disposition: 'close',
          exportInstructions: '',
          notes: 'EXAMPLE: Inactive account - can be deleted',
        },
        {
          id: crypto.randomUUID(),
          platform: 'LinkedIn',
          username: 'John Example',
          disposition: 'memorialize',
          exportInstructions: '',
          notes: 'EXAMPLE: Professional network - memorialize profile',
        },
      ],
      cloudServices: [
        {
          id: crypto.randomUUID(),
          name: 'Personal Backup',
          provider: 'Dropbox',
          status: 'keep',
          billingWarning: true,
          notes: 'EXAMPLE: Important family photos and documents - keep active for 6 months',
        },
        {
          id: crypto.randomUUID(),
          name: 'Development Projects',
          provider: 'GitHub Pro',
          status: 'review',
          billingWarning: false,
          notes: 'EXAMPLE: Contains code repositories - may be valuable to preserve',
        },
        {
          id: crypto.randomUUID(),
          name: 'Email Storage',
          provider: 'Google Workspace',
          status: 'keep',
          billingWarning: true,
          notes: 'EXAMPLE: Archive emails before cancelling - contains important correspondence',
        },
      ],
      domains: [
        {
          id: crypto.randomUUID(),
          name: 'example-personal-site.com',
          registrar: 'Namecheap',
          expirationDate: nearFutureDate,
          notes: 'EXAMPLE: Personal website - consider renewing or letting expire',
        },
        {
          id: crypto.randomUUID(),
          name: 'family-photos-archive.com',
          registrar: 'GoDaddy',
          expirationDate: futureDate,
          notes: 'EXAMPLE: Domain for family photo sharing site - family may want to keep',
        },
      ],
      hosting: [
        {
          id: crypto.randomUUID(),
          provider: 'DigitalOcean',
          accountName: 'Personal Projects',
          renewalDate: nearFutureDate,
          notes: 'EXAMPLE: Hosts personal blog and portfolio - backup data before cancelling',
        },
      ],
    },
    documents: [
      {
        id: crypto.randomUUID(),
        title: 'Last Will and Testament',
        locationType: 'physical',
        location: 'Home Safe',
        details: 'EXAMPLE: Original signed copy',
        notes: 'EXAMPLE: Attorney has a copy - contact Johnson & Associates (555-0200)',
        sensitivity: 'high',
      },
      {
        id: crypto.randomUUID(),
        title: 'Birth Certificate',
        locationType: 'both',
        location: 'Safe Deposit Box #12345, First National Bank',
        details: 'EXAMPLE: Original in bank, scan in ~/Documents/Personal',
        notes: 'EXAMPLE: May need multiple certified copies for various purposes',
        sensitivity: 'high',
      },
      {
        id: crypto.randomUUID(),
        title: 'Property Deed - Main Residence',
        locationType: 'physical',
        location: 'Filing Cabinet, Home Office',
        details: 'EXAMPLE: 123 Main Street, Anytown',
        notes: 'EXAMPLE: Original deed from 2015 purchase',
        sensitivity: 'high',
      },
      {
        id: crypto.randomUUID(),
        title: 'Insurance Policies',
        locationType: 'digital',
        location: '~/Documents/Insurance/',
        details: 'EXAMPLE: Life, Auto, Home insurance documents',
        notes: 'EXAMPLE: Contact State Farm agent Mike Wilson (555-0300) for claims',
        sensitivity: 'normal',
      },
      {
        id: crypto.randomUUID(),
        title: 'Investment Account Statements',
        locationType: 'digital',
        location: 'Fidelity online portal',
        details: 'EXAMPLE: 401k and IRA accounts',
        notes: 'EXAMPLE: Financial advisor: Susan Davis at Fidelity (555-0400)',
        sensitivity: 'high',
      },
      {
        id: crypto.randomUUID(),
        title: 'Vehicle Titles',
        locationType: 'physical',
        location: 'Filing Cabinet, Home Office',
        details: 'EXAMPLE: 2020 Honda Accord, 2018 Toyota RAV4',
        notes: 'EXAMPLE: Paid off, no liens',
        sensitivity: 'normal',
      },
    ],
    emergency: {
      meetingLocations: [
        {
          id: crypto.randomUUID(),
          name: 'City Park Pavilion',
          address: '456 Park Avenue, Anytown',
          notes: 'EXAMPLE: Large covered pavilion near playground - good for group gatherings',
        },
        {
          id: crypto.randomUUID(),
          name: "Aunt Mary's House",
          address: '789 Oak Street, Nearby City',
          notes: 'EXAMPLE: Out of town location if local emergency - has generator',
        },
      ],
      utilityShutoffNotes: 'EXAMPLE:\n\nWATER: Main shutoff valve in basement, left side near water heater. Requires wrench.\n\nGAS: Meter on outside of house, north side. Turn 1/4 turn with adjustable wrench. Call gas company to restore.\n\nELECTRIC: Breaker box in garage. Main breaker at top. Individual circuits labeled.\n\nSEWER: Cleanout valve in basement floor, marked with metal cover.',
      emergencyContacts: [
        {
          id: crypto.randomUUID(),
          name: 'Fire Department',
          relationship: 'Emergency Services',
          phone: '911',
          notes: 'EXAMPLE: For fire, medical emergencies',
        },
        {
          id: crypto.randomUUID(),
          name: 'Dr. Emily Chen',
          relationship: 'Primary Care Physician',
          phone: '555-0500',
          notes: 'EXAMPLE: Central Medical Center - has complete medical history',
        },
        {
          id: crypto.randomUUID(),
          name: 'Tom Wilson',
          relationship: 'Neighbor',
          phone: '555-0600',
          notes: 'EXAMPLE: Lives next door, has spare house key',
        },
        {
          id: crypto.randomUUID(),
          name: 'Lisa Martinez',
          relationship: 'Attorney',
          phone: '555-0700',
          notes: 'EXAMPLE: Johnson & Associates - handles estate matters',
        },
      ],
      grabList: [
        {
          id: crypto.randomUUID(),
          item: 'Important Documents Folder',
          location: 'Home office desk, top right drawer',
          priority: 1,
        },
        {
          id: crypto.randomUUID(),
          item: 'Medications',
          location: 'Bathroom medicine cabinet',
          priority: 2,
        },
        {
          id: crypto.randomUUID(),
          item: 'Phone Chargers',
          location: 'Bedroom nightstand',
          priority: 3,
        },
        {
          id: crypto.randomUUID(),
          item: 'Pet Supplies',
          location: 'Kitchen pantry',
          priority: 4,
        },
        {
          id: crypto.randomUUID(),
          item: 'Family Photo Albums',
          location: 'Living room bookshelf, bottom shelf',
          priority: 5,
        },
        {
          id: crypto.randomUUID(),
          item: 'Laptop and External Hard Drive',
          location: 'Home office desk',
          priority: 6,
        },
      ],
      generalNotes: 'EXAMPLE: This is sample emergency planning information.\n\nGeneral Emergency Preparedness:\n- Emergency supplies stored in basement closet (water, flashlights, first aid)\n- Generator in garage (runs on propane)\n- Emergency cash in home safe ($500)\n- Go-bags prepared for each family member in hall closet\n\nImportant: Replace this demo data with your actual emergency information and plans.',
    },
    willTestaments: {
      sensitivity: 'high',
      willLocation: 'EXAMPLE: Home safe, original with attorney Lisa Martinez',
      trustLocation: 'EXAMPLE: Safe deposit box #12345, First National Bank',
      executor: 'Jane Smith',
      executorContact: '555-0101 / jane.smith@example.com',
      attorney: 'Lisa Martinez',
      attorneyContact: '555-0700 / Johnson & Associates',
      accountant: 'Robert Chen, CPA',
      accountantContact: '555-0800 / rchen@taxadvisors.com',
      estateContacts: [
        {
          id: crypto.randomUUID(),
          type: 'existing',
          existingContactId: contact1Id,
          name: 'Jane Smith',
          relationship: 'Spouse',
          phone: '555-0101',
          email: 'jane.smith@example.com',
          address: '123 Main Street, Anytown, ST 12345',
          notes: 'EXAMPLE: Primary beneficiary and executor',
        },
        {
          id: crypto.randomUUID(),
          type: 'new',
          name: 'David Smith',
          relationship: 'Son',
          phone: '555-0900',
          email: 'david.smith@example.com',
          address: '456 College Avenue, University Town, ST 67890',
          notes: 'EXAMPLE: Secondary beneficiary',
        },
        {
          id: crypto.randomUUID(),
          type: 'new',
          name: 'Emma Smith',
          relationship: 'Daughter',
          phone: '555-1000',
          email: 'emma.smith@example.com',
          address: '789 Career Street, Big City, ST 11111',
          notes: 'EXAMPLE: Secondary beneficiary',
        },
      ],
      assets: [
        {
          id: crypto.randomUUID(),
          name: 'Primary Residence',
          type: 'Real Estate',
          inputMode: 'structured',
          simpleDistribution: '',
          beneficiaries: [
            {
              id: crypto.randomUUID(),
              contactId: contact1Id,
              percentage: 100,
              specificItems: '',
              notes: 'EXAMPLE: Full ownership to spouse',
            },
          ],
          location: '123 Main Street, Anytown, ST 12345',
          estimatedValue: 'EXAMPLE: $450,000',
          notes: 'EXAMPLE: Mortgage paid off in 2020',
        },
        {
          id: crypto.randomUUID(),
          name: 'Investment Portfolio',
          type: 'Financial',
          inputMode: 'simple',
          simpleDistribution: 'EXAMPLE: To be divided equally among spouse and children after estate taxes',
          beneficiaries: [],
          location: 'Fidelity Investments, Account #xxx-xxxxx',
          estimatedValue: 'EXAMPLE: $320,000',
          notes: 'EXAMPLE: Mix of stocks, bonds, and mutual funds',
        },
        {
          id: crypto.randomUUID(),
          name: 'Family Heirlooms and Jewelry',
          type: 'Personal Property',
          inputMode: 'structured',
          simpleDistribution: '',
          beneficiaries: [
            {
              id: crypto.randomUUID(),
              contactId: contact1Id,
              specificItems: "Grandmother's engagement ring, father's watch collection",
              notes: 'EXAMPLE: To distribute to children as she sees fit',
            },
          ],
          location: 'Home safe',
          estimatedValue: 'EXAMPLE: Sentimental value',
          notes: 'EXAMPLE: Detailed inventory list in safe deposit box',
        },
        {
          id: crypto.randomUUID(),
          name: 'Vehicle Collection',
          type: 'Vehicles',
          inputMode: 'simple',
          simpleDistribution: 'EXAMPLE: 2020 Honda Accord to spouse, 2018 Toyota RAV4 to be sold and proceeds divided among children',
          beneficiaries: [],
          location: 'Home garage',
          estimatedValue: 'EXAMPLE: Combined $35,000',
          notes: 'EXAMPLE: Both vehicles paid off, titles in safe',
        },
      ],
      funeralPreferences: 'EXAMPLE: Cremation preferred over burial. Memorial service at St. Mary\'s Church or similar venue.\n\nMusic requests:\n- "Amazing Grace"\n- "What a Wonderful World" by Louis Armstrong\n- Any classical piano pieces\n\nPrefer donations to local animal shelter in lieu of flowers.\n\nCasual dress code for service - celebrate life rather than mourn.\n\nWould like service to include photo slideshow with family pictures.',
      specialInstructions: 'EXAMPLE: Pet Care:\n- Cat (Whiskers) to go to daughter Emma\n- Veterinary records in filing cabinet\n- Preferred vet: Dr. Anderson at Anytown Animal Hospital (555-1100)\n\nDigital Legacy:\n- Social media accounts to be memorialized, not deleted\n- Photo libraries backed up - family should preserve\n- Personal blog can remain active or be archived\n\nSpecial Wishes:\n- College fund for grandchildren priority if funds available\n- Vintage book collection to local library\n- Tools and workshop equipment to nephew who enjoys woodworking',
      generalNotes: 'EXAMPLE: This is sample estate planning information.\n\nImportant: Work with an estate attorney to create or update your will and other legal documents. This tool is for organization only and does not constitute legal advice.\n\nRegular Review: Estate plans should be reviewed every 3-5 years or after major life events (marriage, divorce, births, deaths, significant asset changes).\n\nReplace this demo data with your actual estate planning information.',
    },
    financial: {
      bankAccounts: [
        {
          id: crypto.randomUUID(),
          institution: 'First National Bank',
          accountType: 'Checking',
          accountNumber: '****1234',
          routingNumber: '123456789',
          contactInfo: '555-BANK / www.firstnational.com',
          notes: 'EXAMPLE: Primary checking account for bills and daily expenses',
        },
        {
          id: crypto.randomUUID(),
          institution: 'Community Credit Union',
          accountType: 'Savings',
          accountNumber: '****5678',
          routingNumber: '987654321',
          contactInfo: '555-0950 / www.communitycu.org',
          notes: 'EXAMPLE: Emergency fund savings account',
        },
      ],
      investments: [
        {
          id: crypto.randomUUID(),
          type: 'Brokerage Account',
          institution: 'Fidelity Investments',
          accountNumber: '****9876',
          estimatedValue: 'EXAMPLE: $125,000',
          beneficiaries: 'Spouse: 100%',
          notes: 'EXAMPLE: Mix of index funds and individual stocks',
        },
        {
          id: crypto.randomUUID(),
          type: 'College Savings (529 Plan)',
          institution: 'Vanguard',
          accountNumber: '****4321',
          estimatedValue: 'EXAMPLE: $45,000',
          beneficiaries: 'Children equally',
          notes: 'EXAMPLE: For children\'s education expenses',
        },
      ],
      retirementAccounts: [
        {
          id: crypto.randomUUID(),
          type: '401(k)',
          institution: 'Fidelity (via Employer)',
          accountNumber: '****1111',
          estimatedValue: 'EXAMPLE: $275,000',
          beneficiaries: 'Spouse: 100%',
          notes: 'EXAMPLE: Employer plan with 6% match',
        },
        {
          id: crypto.randomUUID(),
          type: 'Traditional IRA',
          institution: 'Charles Schwab',
          accountNumber: '****2222',
          estimatedValue: 'EXAMPLE: $85,000',
          beneficiaries: 'Spouse: 100%',
          notes: 'EXAMPLE: Rolled over from previous employer',
        },
        {
          id: crypto.randomUUID(),
          type: 'Roth IRA',
          institution: 'Vanguard',
          accountNumber: '****3333',
          estimatedValue: 'EXAMPLE: $52,000',
          beneficiaries: 'Children equally',
          notes: 'EXAMPLE: Annual contributions since 2015',
        },
      ],
      insurancePolicies: [
        {
          id: crypto.randomUUID(),
          type: 'Life Insurance - Term',
          provider: 'State Farm',
          policyNumber: 'LIFE-123456',
          coverageAmount: 'EXAMPLE: $500,000',
          beneficiaries: 'Spouse: 100%',
          notes: 'EXAMPLE: 20-year term, expires 2035. Agent: Mike Wilson 555-0300',
        },
        {
          id: crypto.randomUUID(),
          type: 'Home Insurance',
          provider: 'Allstate',
          policyNumber: 'HOME-789012',
          coverageAmount: 'EXAMPLE: $450,000 dwelling, $100,000 contents',
          beneficiaries: 'Mortgage lender',
          notes: 'EXAMPLE: Includes flood coverage. Renews annually in March',
        },
        {
          id: crypto.randomUUID(),
          type: 'Auto Insurance',
          provider: 'Progressive',
          policyNumber: 'AUTO-345678',
          coverageAmount: 'EXAMPLE: 250/500/100 liability',
          beneficiaries: 'N/A',
          notes: 'EXAMPLE: Covers 2 vehicles. 6-month policy renews May/Nov',
        },
        {
          id: crypto.randomUUID(),
          type: 'Disability Insurance',
          provider: 'Guardian',
          policyNumber: 'DIS-901234',
          coverageAmount: 'EXAMPLE: 60% income replacement',
          beneficiaries: 'Self',
          notes: 'EXAMPLE: Long-term disability through employer',
        },
      ],
      loansDebts: [
        {
          id: crypto.randomUUID(),
          type: 'Home Equity Line of Credit',
          lender: 'First National Bank',
          accountNumber: '****7890',
          balance: 'EXAMPLE: $35,000',
          paymentDetails: 'EXAMPLE: $425/month variable rate, current APR 7.5%',
          coSigners: 'Spouse',
          notes: 'EXAMPLE: Used for home renovations',
        },
        {
          id: crypto.randomUUID(),
          type: 'Auto Loan',
          lender: 'Honda Financial Services',
          accountNumber: '****2468',
          balance: 'EXAMPLE: $12,500',
          paymentDetails: 'EXAMPLE: $385/month, 3.9% APR, 3 years remaining',
          coSigners: 'None',
          notes: 'EXAMPLE: 2020 Honda Accord',
        },
      ],
      creditCards: [
        {
          id: crypto.randomUUID(),
          issuer: 'Chase',
          lastFourDigits: '1234',
          creditLimit: 'EXAMPLE: $15,000',
          paymentInfo: 'EXAMPLE: Autopay setup for minimum payment',
          notes: 'EXAMPLE: Primary card for rewards. Current balance ~$2,500',
        },
        {
          id: crypto.randomUUID(),
          issuer: 'American Express',
          lastFourDigits: '5678',
          creditLimit: 'EXAMPLE: No preset limit',
          paymentInfo: 'EXAMPLE: Pay in full monthly',
          notes: 'EXAMPLE: Business expenses and travel',
        },
      ],
      safeDepositBoxes: [
        {
          id: crypto.randomUUID(),
          bankLocation: 'First National Bank, Downtown Branch',
          boxNumber: '#12345',
          keyLocation: 'Home office desk drawer',
          contents: 'EXAMPLE: Birth certificates, property deed, trust documents, jewelry, rare coins',
          notes: 'EXAMPLE: Spouse has second key. Annual fee $75',
        },
      ],
      financialAdvisors: [
        {
          id: crypto.randomUUID(),
          name: 'Susan Davis',
          company: 'Fidelity Investments',
          phone: '555-0400',
          email: 'susan.davis@fidelity.com',
          servicesProvided: 'EXAMPLE: Investment portfolio management, retirement planning',
          notes: 'EXAMPLE: Quarterly review meetings. Fee-based advisor',
        },
      ],
      accountants: [
        {
          id: crypto.randomUUID(),
          name: 'Robert Chen, CPA',
          company: 'Chen Tax Advisors',
          phone: '555-0800',
          email: 'rchen@taxadvisors.com',
          servicesProvided: 'EXAMPLE: Tax preparation, tax planning, estate planning',
          notes: 'EXAMPLE: Annual tax prep, quarterly estimated tax payments. Has copies of past 7 years of returns',
        },
        {
          id: crypto.randomUUID(),
          name: 'Maria Rodriguez, CPA',
          company: 'Small Business Accounting LLC',
          phone: '555-2100',
          email: 'maria@sbaccounting.com',
          servicesProvided: 'EXAMPLE: Business bookkeeping, payroll, quarterly reports',
          notes: 'EXAMPLE: Handles side business accounting',
        },
      ],
      residualIncome: [
        {
          id: crypto.randomUUID(),
          source: 'Rental Property - 456 Oak Street',
          frequency: 'Monthly',
          amount: 'EXAMPLE: $1,800',
          managementInfo: 'EXAMPLE: Property manager: ABC Rentals (555-2200)',
          notes: 'EXAMPLE: Current tenant lease expires June 2024. Property taxes due annually in November',
        },
        {
          id: crypto.randomUUID(),
          source: 'Book Royalties',
          frequency: 'Quarterly',
          amount: 'EXAMPLE: $500-800',
          managementInfo: 'EXAMPLE: Publisher: Tech Books Press, contact: royalties@techbooks.com',
          notes: 'EXAMPLE: Self-published technical book. Payments via direct deposit',
        },
        {
          id: crypto.randomUUID(),
          source: 'YouTube Ad Revenue',
          frequency: 'Monthly',
          amount: 'EXAMPLE: $200-400',
          managementInfo: 'EXAMPLE: Channel: DIY Home Projects, accessed via personal@example.com',
          notes: 'EXAMPLE: Channel can continue generating revenue or be closed',
        },
      ],
      cryptocurrency: [
        {
          id: crypto.randomUUID(),
          type: 'Exchange Account',
          platform: 'Coinbase',
          holdings: 'EXAMPLE: 0.5 BTC, 5 ETH, various altcoins',
          accessInfo: 'EXAMPLE: Login with personal@example.com, 2FA on phone',
          notes: 'EXAMPLE: Stored on exchange. Recovery phrase in safe deposit box',
        },
        {
          id: crypto.randomUUID(),
          type: 'Hardware Wallet',
          platform: 'Ledger Nano X',
          holdings: 'EXAMPLE: 1.2 BTC, 10 ETH',
          accessInfo: 'EXAMPLE: Wallet in home safe, PIN: see secure notes',
          notes: 'EXAMPLE: 24-word recovery phrase split - half in safe deposit box, half with attorney',
        },
        {
          id: crypto.randomUUID(),
          type: 'DeFi/Staking',
          platform: 'Various protocols',
          holdings: 'EXAMPLE: Staked ETH, liquidity pool positions',
          accessInfo: 'EXAMPLE: Accessed via MetaMask wallet',
          notes: 'EXAMPLE: Complex positions - consider crypto-savvy advisor. Instructions in encrypted file',
        },
      ],
      taxDocuments: [
        {
          id: crypto.randomUUID(),
          year: '2023',
          location: '~/Documents/Taxes/2023/',
          preparerName: 'Robert Chen, CPA',
          preparerContact: '555-0800 / rchen@taxadvisors.com',
          notes: 'EXAMPLE: Filed April 2024. Refund received. Includes Schedule C for side business',
        },
        {
          id: crypto.randomUUID(),
          year: '2022',
          location: '~/Documents/Taxes/2022/',
          preparerName: 'Robert Chen, CPA',
          preparerContact: '555-0800 / rchen@taxadvisors.com',
          notes: 'EXAMPLE: Filed April 2023. Owed additional tax. Includes home office deduction',
        },
        {
          id: crypto.randomUUID(),
          year: '2021',
          location: '~/Documents/Taxes/2021/',
          preparerName: 'TurboTax (self-prepared)',
          preparerContact: 'N/A',
          notes: 'EXAMPLE: Straightforward W-2 filing',
        },
      ],
    },
    notes: [
      {
        id: crypto.randomUUID(),
        title: 'Important Phone Numbers',
        content: 'EXAMPLE:\n\nPlumber: Tom\'s Plumbing 555-1200\nElectrician: Bright Electric 555-1300\nHVAC: Cool Air Services 555-1400\nLandscaping: Green Thumb 555-1500\nHandyman: Fix-It Fred 555-1600',
        category: 'Home Maintenance',
        dateCreated: now,
        dateModified: now,
        isPinned: true,
        color: '#fef3c7',
      },
      {
        id: crypto.randomUUID(),
        title: 'WiFi and Network Info',
        content: 'EXAMPLE:\n\nNetwork Name: HomeNetwork_5G\nPassword: SecurePassword123!\nRouter Location: Hall closet, top shelf\nRouter Admin: 192.168.1.1\nISP: Comcast Business (555-1700)\nAccount #: 1234567890',
        category: 'Technology',
        dateCreated: now,
        dateModified: now,
        isPinned: true,
        color: '#dbeafe',
      },
      {
        id: crypto.randomUUID(),
        title: 'Pet Information',
        content: 'EXAMPLE:\n\nCat: Whiskers (10 years old, tabby)\nVet: Dr. Anderson, Anytown Animal Hospital (555-1100)\nMicrochip #: 123456789012345\nMedications: Thyroid pills daily\nFood: Sensitive stomach formula, feeds 2x daily\nLitter: Clumping, unscented brand',
        category: 'Pets',
        dateCreated: now,
        dateModified: now,
        isPinned: false,
        color: '#fce7f3',
      },
      {
        id: crypto.randomUUID(),
        title: 'Home Security System',
        content: 'EXAMPLE:\n\nProvider: ADT Security\nAccount #: SEC-987654\nMaster Code: 1234\nUser Codes: See separate secure document\nMonitoring: 24/7 with police/fire dispatch\nApp: ADT Control (installed on phones)\nEmergency: 1-800-ADT-ASAP',
        category: 'Security',
        dateCreated: now,
        dateModified: now,
        isPinned: false,
        color: '#f3e8ff',
      },
      {
        id: crypto.randomUUID(),
        title: 'Vehicle Maintenance Schedule',
        content: 'EXAMPLE:\n\n2020 Honda Accord:\n- Oil change every 5,000 miles\n- Last service: 45,000 miles (Jan 2024)\n- Tire rotation every 10,000 miles\n- Mechanic: Joe\'s Auto 555-1800\n\n2018 Toyota RAV4:\n- Oil change every 5,000 miles\n- Last service: 62,000 miles (Dec 2023)\n- Timing belt at 100,000 miles\n- Dealer: Toyota of Anytown 555-1900',
        category: 'Vehicles',
        dateCreated: now,
        dateModified: now,
        isPinned: false,
        color: '#e0e7ff',
      },
    ],
    physicalSecurity: {
      safes: [
        {
          id: crypto.randomUUID(),
          type: 'Home Safe',
          location: 'Master bedroom closet, behind clothing',
          accessMethod: 'EXAMPLE: Electronic keypad - code in secure notes',
          contents: 'EXAMPLE: Passports, jewelry, cash emergency fund, important documents',
          notes: 'EXAMPLE: Fireproof model. Manual override key taped under desk drawer',
        },
        {
          id: crypto.randomUUID(),
          type: 'Gun Safe',
          location: 'Garage, bolted to floor',
          accessMethod: 'EXAMPLE: Biometric + backup key',
          contents: 'EXAMPLE: Firearms inventory list inside. All properly registered',
          notes: 'EXAMPLE: Backup key with attorney. Check state laws regarding transfer',
        },
      ],
      cabinets: [
        {
          id: crypto.randomUUID(),
          type: 'Filing Cabinet',
          location: 'Home office',
          keyLocation: 'EXAMPLE: Kitchen junk drawer',
          contents: 'EXAMPLE: Tax documents, vehicle titles, property deed, insurance policies',
          notes: 'EXAMPLE: Top drawer has most important items',
        },
        {
          id: crypto.randomUUID(),
          type: 'Medication Lock Box',
          location: 'Bathroom cabinet',
          keyLocation: 'EXAMPLE: Combination lock - code same as home alarm',
          contents: 'EXAMPLE: Prescription medications, medical records',
          notes: 'EXAMPLE: Inventory list of current prescriptions inside',
        },
      ],
      securitySystems: [
        {
          id: crypto.randomUUID(),
          provider: 'ADT Security',
          systemType: 'Home Alarm System',
          code: '1234',
          resetInstructions: 'EXAMPLE: Call 1-800-ADT-ASAP with Account #SEC-987654',
          notes: 'EXAMPLE: Monitoring 24/7. Motion sensors, door/window sensors, cameras. User codes in secure notes.',
        },
        {
          id: crypto.randomUUID(),
          provider: 'Ring',
          systemType: 'Video Doorbell & Cameras',
          code: '',
          resetInstructions: 'EXAMPLE: Access via app on phone, linked to personal@example.com',
          notes: 'EXAMPLE: 4 cameras total - front door, back door, driveway, garage. Spouse also has access.',
        },
      ],
      physicalKeys: [
        {
          id: crypto.randomUUID(),
          keyFor: 'House - Front & Back Doors',
          quantity: 'EXAMPLE: 4 copies',
          locations: 'EXAMPLE: 1 primary keychain, 1 with spouse, 1 with neighbor Tom Wilson, 1 hidden under decorative rock by back patio',
          notes: 'EXAMPLE: Locks should be rekeyed after access by estate executor',
        },
        {
          id: crypto.randomUUID(),
          keyFor: 'Safe Deposit Box',
          quantity: 'EXAMPLE: 2 copies',
          locations: 'EXAMPLE: 1 home office desk drawer, 1 with spouse',
          notes: 'EXAMPLE: Bank requires ID and signature card for access',
        },
        {
          id: crypto.randomUUID(),
          keyFor: 'Vehicle Spare Keys',
          quantity: 'EXAMPLE: 2 sets',
          locations: 'EXAMPLE: Magnetic hide-a-key under each vehicle',
          notes: 'EXAMPLE: Smart keys - may need programming for new user',
        },
        {
          id: crypto.randomUUID(),
          keyFor: 'Storage Unit',
          quantity: 'EXAMPLE: 2 copies',
          locations: 'EXAMPLE: Both on personal keychain',
          notes: 'EXAMPLE: Unit #245 at Store-All, 789 Storage Lane. Rent paid annually in March',
        },
      ],
    },
    securityRecovery: {
      securityQuestions: [
        {
          id: crypto.randomUUID(),
          account: 'Primary Email (Gmail)',
          question: 'EXAMPLE: What was your first pet\'s name?',
          answerHint: 'EXAMPLE: Childhood dog, golden retriever',
          notes: 'EXAMPLE: Answer is stored in password manager',
        },
        {
          id: crypto.randomUUID(),
          account: 'Bank Account',
          question: 'EXAMPLE: What street did you grow up on?',
          answerHint: 'EXAMPLE: Childhood address street name only',
          notes: 'EXAMPLE: Answer in secure notes document',
        },
        {
          id: crypto.randomUUID(),
          account: 'Investment Account',
          question: 'EXAMPLE: What was your high school mascot?',
          answerHint: 'EXAMPLE: High school in hometown',
          notes: 'EXAMPLE: Answer shared with spouse',
        },
        {
          id: crypto.randomUUID(),
          account: 'Amazon',
          question: 'EXAMPLE: What is your mother\'s maiden name?',
          answerHint: 'EXAMPLE: Maternal grandmother\'s last name',
          notes: 'EXAMPLE: Common recovery question - verify with family',
        },
      ],
      backupCodes: 'EXAMPLE: Two-factor authentication backup codes stored in multiple locations:\n\n1. Password manager (primary location)\n2. Printed copy in home safe\n3. Encrypted file on NAS backup\n4. Copy with attorney in sealed envelope\n\nCodes should be used to gain access to 2FA-protected accounts. Each code can typically only be used once.',
      recoveryNotes: 'EXAMPLE: Account Recovery Process:\n\n1. Email accounts: Use password manager for credentials, backup codes for 2FA\n2. Banking: May require death certificate + executor documentation\n3. Social media: Use legacy contact feature (Facebook) or memorialization request\n4. Apple ID: Legacy contact feature activated - spouse has access\n5. Google: Inactive account manager set up - spouse receives access after 3 months\n\nGeneral tips:\n- Most services have specific procedures for deceased users\n- Death certificate will be required for financial accounts\n- Executor documentation required for many official actions\n- Some accounts can\'t be transferred, only closed or memorialized',
    },
  };
}
